# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: sync-and-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Unit test
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-java@v4
      #   with:
      #     java-version: "8"
      #     distribution: "temurin"
      # - name: "Local unit test with Maven"
      #   run: mvn clean test

  # Sync designtime artifact to tenant
  sync:
    runs-on: ubuntu-latest
    # needs: unit_test
    container:
      image: engswee/flashpipe:latest
    steps:
      - uses: actions/checkout@v4

      - name: "Update/Upload DemoFlow to design time"
        uses: engswee/flashpipe-action/sync@v1
        with:
          tmn-host: asc-isuite-prod.integrationsuite.cfapps.eu20-001.hana.ondemand.com
          oauth-host: asc-isuite-prod.authentication.eu20.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          target: tenant
          package-id: TestErrors

  # Deploy to runtime
  deploy:
    runs-on: ubuntu-latest
    needs: sync
    container:
      image: engswee/flashpipe:latest
    steps:
      - uses: actions/checkout@v4

      - name: "Deploy DemoFlow to runtime"
        uses: engswee/flashpipe-action/deploy@v1
        with:
          tmn-host: asc-isuite-prod.integrationsuite.cfapps.eu20-001.hana.ondemand.com
          oauth-host: equaliseit.authentication.eu20.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          artifact-ids: DemoFlow
